server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

spring:
  application:
    name: CART-SERVICE

#To show the actuator endpoints 
management:  endpoints:    web:      exposure:        include: '*'