server:
  port: 8081

eureka:  client:    service-url:      default-zone: http://localhost:8761/

spring:#  datasource:#    url: jdbc:mysql://localhost:3306/training
#    username: root
#    password: sudheer#  jpa:#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
#    hibernate:#      ddl-auto: update
  application:    name: MOBILE-SERVICE  config:    import: configserver:http://localhost:8888
  profiles:    active: prod, dev