server:
  port: 8761

#http://localhost:8761 is the url of the service registry  

eureka:  instance:    hostname: localhost
  client:    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}    
    fetch-registry: false  # this is a registry do not fetch registry is true. so change to false    register-with-eureka: false  #this is a registry.so do not self register  